[package]
name = "rusty-chip-8"
version = "0.1.0"
authors = ["Mihail Odebe <derpiranha@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
sdl2 = "0.34"
clap = "3.0.0-beta.2"
